// Generated by `bun init`

declare module "*.svg" {
    /**
     * A path to the SVG file
     */
    const src: string;
    export default src;
}

declare module "*.png" {
    /**
     * A path to the PNG file
     */
    const src: string;
    export default src;
}
  
declare module "*.module.css" {
    /**
     * A record of class names to their corresponding CSS module classes
     */
    const classes: { readonly [key: string]: string };
    export = classes;
}
